"""add ueaglider bool to glider table

Revision ID: 1fabdd70ac20
Revises: ed69a9dfbbd2
Create Date: 2021-02-18 13:20:04.048735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fabdd70ac20'
down_revision = 'ed69a9dfbbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gliders', sa.Column('UEAGlider', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gliders', 'UEAGlider')
    # ### end Alembic commands ###
