"""added datetime to dive

Revision ID: 2d2caa1e217e
Revises: f27768eb1768
Create Date: 2021-02-16 10:17:32.605184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d2caa1e217e'
down_revision = 'f27768eb1768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiveInfo', sa.Column('ReceivedDate', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DiveInfo', 'ReceivedDate')
    # ### end Alembic commands ###
