"""Adding waypoint date

Revision ID: 41b8cd9ae94f
Revises: e5cdef56a782
Create Date: 2021-01-14 17:59:04.842093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b8cd9ae94f'
down_revision = 'e5cdef56a782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'DiveInfo', 'Missions', ['MissionID'], ['MissionID'])
    op.create_foreign_key(None, 'Targets', 'Missions', ['MissionID'], ['MissionID'])
    op.add_column('Waypoints', sa.Column('StartDate', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'Waypoints', 'Missions', ['MissionID'], ['MissionID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Waypoints', 'StartDate')
    # ### end Alembic commands ###
