"""Adding foreign key relations

Revision ID: e5cdef56a782
Revises: 
Create Date: 2021-01-14 17:49:44.570101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5cdef56a782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'DiveInfo', 'Missions', ['MissionID'], ['MissionID'])
    op.alter_column('Gliders', 'Number',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.alter_column('Missions', 'Number',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.create_foreign_key(None, 'Targets', 'Missions', ['MissionID'], ['MissionID'])
    op.create_foreign_key(None, 'Waypoints', 'Missions', ['MissionID'], ['MissionID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Waypoints', type_='foreignkey')
    op.drop_constraint(None, 'Targets', type_='foreignkey')
    op.alter_column('Missions', 'Number',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('Gliders', 'Number',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.drop_constraint(None, 'DiveInfo', type_='foreignkey')
    # ### end Alembic commands ###
