"""added dive depth

Revision ID: ed69a9dfbbd2
Revises: 2d2caa1e217e
Create Date: 2021-02-16 12:00:16.233665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed69a9dfbbd2'
down_revision = '2d2caa1e217e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiveInfo', sa.Column('Elevation', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DiveInfo', 'Elevation')
    # ### end Alembic commands ###
